# Generated by Django 4.0.3 on 2022-04-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resto_id', models.IntegerField()),
                ('resto_name', models.CharField(max_length=255)),
                ('resto_address', models.CharField(max_length=255)),
                ('resto_description', models.TextField(default='null')),
                ('kuhnya', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('namazhana', models.CharField(default='null', max_length=255)),
                ('contacts', models.CharField(default='null', max_length=255)),
                ('certificate', models.CharField(max_length=255)),
                ('menu', models.ImageField(null=True, upload_to='images/', verbose_name='')),
                ('resto_photo', models.ImageField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
    ]
