# Generated by Django 4.0.3 on 2022-04-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_restaurants_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='certificate',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='menu',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
