# Generated by Django 4.0.3 on 2022-04-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_restaurants_certificate_alter_restaurants_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mosque_name', models.CharField(max_length=100)),
                ('mosque_description', models.TextField(default='null')),
                ('mosque_address', models.CharField(max_length=100)),
                ('mosque_contacts', models.CharField(default='null', max_length=100)),
                ('mosque_photo', models.ImageField(null=True, upload_to='images/', verbose_name='')),
                ('mosque_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('resto_id', models.IntegerField()),
                ('review', models.TextField(default='null')),
                ('rate', models.IntegerField()),
                ('review_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=100)),
                ('user_lname', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=65)),
            ],
        ),
    ]
