# Generated by Django 4.0.3 on 2022-04-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_mosque_reviews_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='certificate',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='certificate'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='resto_photo',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='photo'),
        ),
    ]
